version: '3'
services:
  db-dev:
    image: postgres
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
  db-test:
    image: postgres
    restart: always
    ports:
      - 127.0.0.1:5433:5432
    environment:
      POSTGRES_PASSWORD: "testing!"
