name: "coverage"

on:
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.0.2
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: pnpm
